// Static seed data — REAL Sera Property listings sourced from their Facebook & YouTube
// https://www.facebook.com/SeraPropertyBD/

export interface SeedProperty {
  id: string;
  title: string;
  location: string;
  area: string;
  price: number;
  priceUnit: string;
  bedrooms: number | null;
  bathrooms: number | null;
  sqft: number | null;
  type: string;
  category: string | null;
  spaceType: string | null;
  furnished: string;
  featured: boolean;
  hasView: boolean;
  imageUrl: string;
  imageUrls: string;
  description: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface SeedBlogPost {
  id: string;
  title: string;
  excerpt: string;
  imageUrl: string | null;
  author: string | null;
  readTime: string | null;
  publishedAt: string | null;
}

const now = new Date().toISOString();

export const seedProperties: SeedProperty[] = [
  // ===== RESIDENTIAL (8) — Real Sera Property listings =====
  {
    id: "sp-res-1",
    title: "Ultra-Luxury 3500 Sq Ft Apartment in Bashundhara R/A",
    location: "Bashundhara R/A, Dhaka",
    area: "Bashundhara",
    price: 85000,
    priceUnit: "per month",
    bedrooms: 4,
    bathrooms: 5,
    sqft: 3500,
    type: "residential",
    category: "Apartment",
    spaceType: null,
    furnished: "Furnished",
    featured: true,
    hasView: true,
    imageUrl: "/images/properties/apt1.png",
    imageUrls: "[]",
    description: "Ultra-luxury 4-bedroom apartment with 5 modern bathrooms, servant quarter, and prime location in Bashundhara R/A. Features premium finishes, spacious living areas, and world-class amenities. Live in style with Sera Property.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sp-res-2",
    title: "Spacious 2675 Sq Ft 3-Bedroom Apartment in Bashundhara",
    location: "Bashundhara R/A, Dhaka",
    area: "Bashundhara",
    price: 55000,
    priceUnit: "per month",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2675,
    type: "residential",
    category: "Apartment",
    spaceType: null,
    furnished: "Semi-Furnished",
    featured: true,
    hasView: true,
    imageUrl: "/images/properties/apt2.png",
    imageUrls: "[]",
    description: "Well-planned 2675 sq ft apartment featuring 3 spacious bedrooms, 3 modern bathrooms, and 4 balconies. Located in prime Bashundhara Residential Area with 2 car parking and servant accommodation.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sp-res-3",
    title: "Move-In Ready Fully Furnished 2400 Sq Ft | Banani",
    location: "Banani, Dhaka",
    area: "Banani",
    price: 65000,
    priceUnit: "per month",
    bedrooms: 3,
    bathrooms: 4,
    sqft: 2400,
    type: "residential",
    category: "Apartment",
    spaceType: null,
    furnished: "Furnished",
    featured: true,
    hasView: true,
    imageUrl: "/images/properties/apt3.png",
    imageUrls: "[]",
    description: "Experience premium living in this fully furnished 2400 sq ft apartment on the 4th floor in Banani. Features 3 bedrooms, 4 bathrooms, modern kitchen, and stunning city views. Move-in ready with Sera Property.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sp-res-4",
    title: "Modern 2500 Sq Ft Semi-Furnished Apartment in Bashundhara R/A",
    location: "Bashundhara R/A, Dhaka",
    area: "Bashundhara",
    price: 45000,
    priceUnit: "per month",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2500,
    type: "residential",
    category: "Apartment",
    spaceType: null,
    furnished: "Semi-Furnished",
    featured: true,
    hasView: false,
    imageUrl: "/images/properties/apt4.png",
    imageUrls: "[]",
    description: "A well-planned 2500 sq ft apartment in Bashundhara R/A offering 3 spacious bedrooms with 3 modern bathrooms. Modern design with ample natural light and ventilation. Property ID: RB24182.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sp-res-5",
    title: "Premium 2-Room Serviced Apartment | Bashundhara R/A",
    location: "Bashundhara R/A, Dhaka",
    area: "Bashundhara",
    price: 38000,
    priceUnit: "per month",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1600,
    type: "residential",
    category: "Apartment",
    spaceType: null,
    furnished: "Furnished",
    featured: true,
    hasView: false,
    imageUrl: "/images/properties/apt5.png",
    imageUrls: "[]",
    description: "Premium fully furnished 2-room serviced apartment in one of Dhaka's most secure neighborhoods. Ideal for expats and professionals seeking a hassle-free rental experience in Bashundhara R/A.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sp-res-6",
    title: "Best Deal! 2150 Sq Ft Apartment Rent Only 50K | Bashundhara",
    location: "Bashundhara R/A, Dhaka",
    area: "Bashundhara",
    price: 50000,
    priceUnit: "per month",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2150,
    type: "residential",
    category: "Apartment",
    spaceType: null,
    furnished: "Unfurnished",
    featured: true,
    hasView: false,
    imageUrl: "/images/properties/apt6.png",
    imageUrls: "[]",
    description: "Best value 2150 sq ft apartment including service charge at just ৳50,000/month in Bashundhara R/A. Features 3 bedrooms, 3 bathrooms, and 2 balconies with modern amenities.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sp-res-7",
    title: "1900 Sq Ft Semi-Furnished Apartment in Bashundhara R/A",
    location: "Bashundhara R/A, Dhaka",
    area: "Bashundhara",
    price: 35000,
    priceUnit: "per month",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1900,
    type: "residential",
    category: "Apartment",
    spaceType: null,
    furnished: "Semi-Furnished",
    featured: true,
    hasView: false,
    imageUrl: "/images/properties/apt7.png",
    imageUrls: "[]",
    description: "Spacious 1900 sq ft semi-furnished apartment featuring 3 bedrooms, 3 modern bathrooms, and servant accommodation. Prime location in Bashundhara Residential Area with easy access to schools and shopping.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sp-res-8",
    title: "Exclusive 2250 Sq Ft Full Furnished Apartment | Banani",
    location: "Banani, Dhaka",
    area: "Banani",
    price: 70000,
    priceUnit: "per month",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2250,
    type: "residential",
    category: "Apartment",
    spaceType: null,
    furnished: "Furnished",
    featured: true,
    hasView: true,
    imageUrl: "/images/properties/apt8.png",
    imageUrls: "[]",
    description: "Exclusive full-furnished apartment in North Banani with stunning south-facing city view. 2250 sq ft of premium living space with modern kitchen, spacious bedrooms, and dedicated parking.",
    createdAt: now,
    updatedAt: now,
  },

  // ===== COMMERCIAL (4) — Real Sera Property listings =====
  {
    id: "sp-com-1",
    title: "Spacious 3700 Sq Ft 5-Bed Duplex for Rent | Bashundhara",
    location: "Bashundhara R/A, Dhaka",
    area: "Bashundhara",
    price: 75000,
    priceUnit: "per month",
    bedrooms: 5,
    bathrooms: 5,
    sqft: 3700,
    type: "commercial",
    category: "Commercial Space",
    spaceType: "Enclosed Space",
    furnished: "Unfurnished",
    featured: true,
    hasView: true,
    imageUrl: "/images/properties/comm1.png",
    imageUrls: "[]",
    description: "Discover luxurious living in this expansive 3700 sq ft 5-bedroom duplex apartment located in the heart of Bashundhara. Ideal for corporate housing or large families needing premium space.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sp-com-2",
    title: "Premium Open-Plan Office Space | Bashundhara R/A",
    location: "Bashundhara R/A, Dhaka",
    area: "Bashundhara",
    price: 65000,
    priceUnit: "per month",
    bedrooms: null,
    bathrooms: null,
    sqft: 2500,
    type: "commercial",
    category: "Office Space",
    spaceType: "Open Space",
    furnished: "Unfurnished",
    featured: true,
    hasView: false,
    imageUrl: "/images/properties/comm2.png",
    imageUrls: "[]",
    description: "Modern open-plan office space in Bashundhara R/A with flexible layout options. Perfect for startups, tech companies, or creative agencies looking for a professional workspace in a prime Dhaka location.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sp-com-3",
    title: "Fully Fitted Commercial Space for Rent | Gulshan",
    location: "Gulshan, Dhaka",
    area: "Gulshan",
    price: 120000,
    priceUnit: "per month",
    bedrooms: null,
    bathrooms: null,
    sqft: 3000,
    type: "commercial",
    category: "Commercial Space",
    spaceType: "Enclosed Space",
    furnished: "Semi-Furnished",
    featured: true,
    hasView: false,
    imageUrl: "/images/properties/comm3.png",
    imageUrls: "[]",
    description: "Fully fitted commercial space in Gulshan ideal for retail, showroom, or corporate office. Features modern interiors, central AC, power backup, and dedicated parking in Dhaka's premier business district.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sp-com-4",
    title: "Modern Serviced Office | Banani",
    location: "Banani, Dhaka",
    area: "Banani",
    price: 45000,
    priceUnit: "per month",
    bedrooms: null,
    bathrooms: null,
    sqft: 1800,
    type: "commercial",
    category: "Office Space",
    spaceType: "Enclosed Space",
    furnished: "Furnished",
    featured: true,
    hasView: true,
    imageUrl: "/images/properties/comm4.png",
    imageUrls: "[]",
    description: "Modern furnished serviced office space in Banani with meeting rooms, high-speed internet, and 24/7 security. Move-in ready for businesses seeking a prestigious Dhaka address with all amenities included.",
    createdAt: now,
    updatedAt: now,
  },
];

export const seedBlogPosts: SeedBlogPost[] = [
  {
    id: "sp-blog-1",
    title: "Understanding Dhaka's Rental Market in 2026",
    excerpt:
      "A comprehensive look at how Dhaka's rental landscape is evolving with new trends in Bashundhara, Gulshan, and Banani. Learn about price movements, tenant preferences, and what to expect this year.",
    imageUrl: "/images/blog/blog1.png",
    author: "Sera Property Team",
    readTime: "5 mins read",
    publishedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "sp-blog-2",
    title: "Living in Bashundhara R/A: The Complete Neighborhood Guide",
    excerpt:
      "Explore why Bashundhara Residential Area has become one of Dhaka's most sought-after neighborhoods. From schools and hospitals to shopping malls and restaurants — everything you need to know.",
    imageUrl: "/images/blog/blog2.png",
    author: "Sera Property Team",
    readTime: "4 mins read",
    publishedAt: "2026-03-15T00:00:00.000Z",
  },
  {
    id: "sp-blog-3",
    title: "Furnished vs Unfurnished: Which Is Right for You?",
    excerpt:
      "Deciding between furnished and unfurnished apartments in Dhaka? We break down the costs, pros, and cons to help you make the best rental decision for your lifestyle and budget.",
    imageUrl: "/images/blog/blog3.png",
    author: "Sera Property Team",
    readTime: "3 mins read",
    publishedAt: "2026-02-20T00:00:00.000Z",
  },
  {
    id: "sp-blog-4",
    title: "Rental Price Trends: What Tenants Need to Know in 2026",
    excerpt:
      "An in-depth analysis of rental price movements across Dhaka's premium areas — Bashundhara, Gulshan, Banani, and Baridhara. Data-driven insights to help you negotiate the best deal.",
    imageUrl: "/images/blog/blog1.png",
    author: "Sera Property Team",
    readTime: "3 mins read",
    publishedAt: "2025-12-10T00:00:00.000Z",
  },
  {
    id: "sp-blog-5",
    title: "The Future of Property Rentals in Bangladesh",
    excerpt:
      "How technology and professional letting agencies like Sera Property are transforming the rental experience in Dhaka with verified listings, virtual tours, and transparent pricing.",
    imageUrl: "/images/blog/blog2.png",
    author: "Sera Property Team",
    readTime: "4 mins read",
    publishedAt: "2025-11-05T00:00:00.000Z",
  },
  {
    id: "sp-blog-6",
    title: "Tips for First-Time Renters in Dhaka",
    excerpt:
      "Essential guide for anyone renting their first apartment in Dhaka — from documentation and security deposits to understanding lease agreements and negotiating with landlords.",
    imageUrl: "/images/blog/blog3.png",
    author: "Sera Property Team",
    readTime: "6 mins read",
    publishedAt: "2025-10-18T00:00:00.000Z",
  },
];